services:
  db:
    image: postgres:16
    container_name: hero-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hero
      POSTGRES_USER: hero
      POSTGRES_PASSWORD: hero
    ports:
      - "5432:5432"   # host:container
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hero -d hero"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  dbdata:
