name: client-ci
on:
  push:
    paths:
      - "apps/client/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/client-ci.yml"
  pull_request:
    paths:
      - "apps/client/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/client-ci.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      # actually install pnpm
      - run: corepack enable
      - run: corepack prepare pnpm@9 --activate
      - run: pnpm -v

      # install once at the workspace root, then build the client
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/client build
